<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Users
        DB::table('users')->insert([
            'name' => 'admin',
            'email' => 'admin@123',
            'email_verified_at' => now(),
            'password' => Hash::make('123'),
            'nowhatsap' => '081234567890',
            'maps' => 'https://maps.google.com',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Blogs
        DB::table('blogs')->insert(
           [
    [
        'title' => 'Judul Blog Pertama',
        'description' => 'Deskripsi singkat blog pertama.',
        'content' => '<p>Isi konten lengkap blog pertama.</p>',
        'thumbnail' => 'blog1.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Kedua',
        'description' => 'Deskripsi singkat blog kedua.',
        'content' => '<p>Isi konten lengkap blog kedua.</p>',
        'thumbnail' => 'blog2.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Ketiga',
        'description' => 'Deskripsi singkat blog ketiga.',
        'content' => '<p>Isi konten lengkap blog ketiga.</p>',
        'thumbnail' => 'blog3.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Keempat',
        'description' => 'Deskripsi singkat blog keempat.',
        'content' => '<p>Isi konten lengkap blog keempat.</p>',
        'thumbnail' => 'blog4.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Kelima',
        'description' => 'Deskripsi singkat blog kelima.',
        'content' => '<p>Isi konten lengkap blog kelima.</p>',
        'thumbnail' => 'blog5.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Keenam',
        'description' => 'Deskripsi singkat blog keenam.',
        'content' => '<p>Isi konten lengkap blog keenam.</p>',
        'thumbnail' => 'blog6.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Ketujuh',
        'description' => 'Deskripsi singkat blog ketujuh.',
        'content' => '<p>Isi konten lengkap blog ketujuh.</p>',
        'thumbnail' => 'blog7.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Kedelapan',
        'description' => 'Deskripsi singkat blog kedelapan.',
        'content' => '<p>Isi konten lengkap blog kedelapan.</p>',
        'thumbnail' => 'blog8.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Kesembilan',
        'description' => 'Deskripsi singkat blog kesembilan.',
        'content' => '<p>Isi konten lengkap blog kesembilan.</p>',
        'thumbnail' => 'blog9.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Judul Blog Kesepuluh',
        'description' => 'Deskripsi singkat blog kesepuluh.',
        'content' => '<p>Isi konten lengkap blog kesepuluh.</p>',
        'thumbnail' => 'blog10.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
]
);

        // Products
        DB::table('products')->insert([
        [
        'title' => 'Properti A',
        'location' => 'Jakarta Selatan',
        'deskripsi' => 'Deskripsi properti A',
        'image' => 'produk1.jpg',
        'badge' => 'Baru',
        'features' => 'Kolam Renang, AC, Garasi',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Rumah',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '3 Kamar, 2 Kamar Mandi',
        'properti_fasilitas' => 'WiFi, Keamanan 24 jam',
        'properti_pembayaran' => 'Cash/KPR',
        'price' => 1500000000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti B',
        'location' => 'Bandung',
        'deskripsi' => 'Deskripsi properti B',
        'image' => 'produk2.jpg',
        'badge' => 'Populer',
        'features' => 'Taman, Balkon, AC',
        'popular' => false,
        'date' => now(),
        'tipe' => 'Apartemen',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '2 Kamar, 1 Kamar Mandi',
        'properti_fasilitas' => 'Kolam Renang, Gym',
        'properti_pembayaran' => 'Cash',
        'price' => 900000000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti C',
        'location' => 'Surabaya',
        'deskripsi' => 'Deskripsi properti C',
        'image' => 'produk3.jpg',
        'badge' => 'Diskon',
        'features' => 'Garasi, AC, Taman',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Ruko',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '4 Kamar, 3 Kamar Mandi',
        'properti_fasilitas' => 'Parkir Luas, Keamanan 24 jam',
        'properti_pembayaran' => 'KPR',
        'price' => 2000000000,
        'created_at' => now(),
        'updated_at' => now(),
    ],   

    
    [
        'title' => 'Properti 21',
        'location' => 'Depok',
        'deskripsi' => 'Deskripsi properti 21',
        'image' => 'produk21.jpg',
        'badge' => 'Baru',
        'features' => 'Kolam Renang, AC, Taman',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Rumah',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '4 Kamar, 2 Kamar Mandi',
        'properti_fasilitas' => 'WiFi, CCTV',
        'properti_pembayaran' => 'Cash/KPR',
        'price' => 1750000000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 22',
        'location' => 'Bogor',
        'deskripsi' => 'Deskripsi properti 22',
        'image' => 'produk22.jpg',
        'badge' => 'Diskon',
        'features' => 'Balkon, AC',
        'popular' => false,
        'date' => now(),
        'tipe' => 'Apartemen',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '2 Kamar, 1 Kamar Mandi',
        'properti_fasilitas' => 'Gym, Keamanan 24 jam',
        'properti_pembayaran' => 'KPR',
        'price' => 950000000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 23',
        'location' => 'Tangerang',
        'deskripsi' => 'Deskripsi properti 23',
        'image' => 'produk23.jpg',
        'badge' => 'Populer',
        'features' => 'AC, Garasi',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Ruko',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '3 Kamar, 3 Kamar Mandi',
        'properti_fasilitas' => 'Parkir Luas, CCTV',
        'properti_pembayaran' => 'Cash',
        'price' => 230000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 24',
        'location' => 'Bekasi',
        'deskripsi' => 'Deskripsi properti 24',
        'image' => 'produk24.jpg',
        'badge' => 'Baru',
        'features' => 'Kolam Renang, Balkon',
        'popular' => false,
        'date' => now(),
        'tipe' => 'Rumah',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '5 Kamar, 4 Kamar Mandi',
        'properti_fasilitas' => 'Kolam Renang, Keamanan 24 jam',
        'properti_pembayaran' => 'Cash/KPR',
        'price' => 30000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 25',
        'location' => 'Yogyakarta',
        'deskripsi' => 'Deskripsi properti 25',
        'image' => 'produk25.jpg',
        'badge' => 'Diskon',
        'features' => 'Taman, Garasi',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Villa',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '4 Kamar, 2 Kamar Mandi',
        'properti_fasilitas' => 'WiFi, CCTV, Kolam Renang',
        'properti_pembayaran' => 'Cash/KPR',
        'price' => 2750000,
        'created_at' => now(),
        'updated_at' => now(),
    ],

    [
        'title' => 'Properti 26',
        'location' => 'Malang',
        'deskripsi' => 'Deskripsi properti 26',
        'image' => 'produk26.jpg',
        'badge' => 'Baru',
        'features' => 'Taman, Garasi, Balkon',
        'popular' => false,
        'date' => now(),
        'tipe' => 'Rumah',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '3 Kamar, 2 Kamar Mandi',
        'properti_fasilitas' => 'WiFi, Keamanan 24 jam',
        'properti_pembayaran' => 'Cash',
        'price' => 1200000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 27',
        'location' => 'Semarang',
        'deskripsi' => 'Deskripsi properti 27',
        'image' => 'produk27.jpg',
        'badge' => 'Populer',
        'features' => 'Kolam Renang, Balkon',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Villa',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '4 Kamar, 3 Kamar Mandi',
        'properti_fasilitas' => 'Gym, Kolam Renang',
        'properti_pembayaran' => 'Cash/KPR',
        'price' => 2500000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 28',
        'location' => 'Makassar',
        'deskripsi' => 'Deskripsi properti 28',
        'image' => 'produk28.jpg',
        'badge' => 'Diskon',
        'features' => 'AC, Garasi',
        'popular' => false,
        'date' => now(),
        'tipe' => 'Ruko',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '2 Kamar, 1 Kamar Mandi',
        'properti_fasilitas' => 'Parkir Luas, CCTV',
        'properti_pembayaran' => 'KPR',
        'price' => 1000000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 29',
        'location' => 'Palembang',
        'deskripsi' => 'Deskripsi properti 29',
        'image' => 'produk29.jpg',
        'badge' => 'Baru',
        'features' => 'Taman, Balkon, AC',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Rumah',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '3 Kamar, 2 Kamar Mandi',
        'properti_fasilitas' => 'WiFi, Keamanan 24 jam',
        'properti_pembayaran' => 'Cash/KPR',
        'price' => 1600000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 30',
        'location' => 'Cirebon',
        'deskripsi' => 'Deskripsi properti 30',
        'image' => 'produk30.jpg',
        'badge' => 'Diskon',
        'features' => 'Taman, Garasi',
        'popular' => false,
        'date' => now(),
        'tipe' => 'Ruko',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '2 Kamar, 2 Kamar Mandi',
        'properti_fasilitas' => 'CCTV, Area Komersial',
        'properti_pembayaran' => 'Cash',
        'price' => 11000000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'title' => 'Properti 31',
        'location' => 'Bali',
        'deskripsi' => 'Deskripsi properti 31',
        'image' => 'produk31.jpg',
        'badge' => 'Populer',
        'features' => 'Kolam Renang, Taman, Balkon',
        'popular' => true,
        'date' => now(),
        'tipe' => 'Villa',
        'maps' => 'https://maps.google.com',
        'properti_detail' => '5 Kamar, 4 Kamar Mandi',
        'properti_fasilitas' => 'Spa, Keamanan 24 jam, WiFi',
        'properti_pembayaran' => 'Cash/KPR',
        'price' => 350000000,
        'created_at' => now(),
        'updated_at' => now(),
    ]   
        ]);

        // Ratings
        DB::table('ratings')->insert([
            [
                'nama' => 'Andi',
                'ulasan' => 'Properti bagus dan nyaman!',
                'total_rate' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Budi',
                'ulasan' => 'Cukup memuaskan.',
                'total_rate' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
    [
        'nama' => 'Citra',
        'ulasan' => 'Lokasi strategis dan pelayanan ramah.',
        'total_rate' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nama' => 'Dedi',
        'ulasan' => 'Harga sesuai dengan kualitas.',
        'total_rate' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nama' => 'Eka',
        'ulasan' => 'Kondisi properti perlu diperbaiki.',
        'total_rate' => 3,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nama' => 'Fani',
        'ulasan' => 'Lingkungan sekitar nyaman dan aman.',
        'total_rate' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nama' => 'Gilang',
        'ulasan' => 'Desain rumah modern dan menarik.',
        'total_rate' => 5,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nama' => 'Hana',
        'ulasan' => 'Proses transaksi mudah dan cepat.',
        'total_rate' => 4,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'nama' => 'Ivan',
        'ulasan' => 'Kurang puas dengan fasilitas yang disediakan.',
        'total_rate' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ]


        ]);

        // Sosmeds
        DB::table('sosmeds')->insert([
            [
                'username' => '@syofian',
                'medsos' => 'Instagram',
                'icon' => 'fab fa-instagram',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '@syofianfb',
                'medsos' => 'Facebook',
                'icon' => 'fab fa-facebook',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
